find_program(CCACHE_FOUND ccache)
if (CCACHE_FOUND)
    message(STATUS "ccache found, using ccache")
    set(CMAKE_CXX_COMPILER_LAUNCHER ccache)
else ()
    message(STATUS "ccache not found")
endif ()